global:
  scrape_interval: 5s  # Default scrape interval for all targets
  evaluation_interval: 15s  # Default evaluation interval for rules

scrape_configs:
  - job_name: 'LocalBookstore'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s

    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # HTTP target
        labels:
          application: 'Bookstore Spring Boot Application'
          instance: 'local_instance'

  - job_name: 'RemoteDevBookstore'
    metrics_path: '/actuator/prometheus'
    # Use HTTP and the proxy as the target
    scheme: http
    static_configs:
      - targets:
          - 'nginx_dev_proxy:80'
        labels:
          application: 'Bookstore Spring Boot Application'
          instance: 'dev_instance'

  - job_name: 'RemoteProdBookstore'
    metrics_path: '/actuator/prometheus'
    # Use HTTP and the proxy as the target
    scheme: http
    static_configs:
      - targets:
          - 'nginx_prod_proxy:80'
        labels:
          application: 'Bookstore Spring Boot Application'
          instance: 'prod_instance'
