services:
  backend:
    image: bookstore_backend:aws-alpine
    build: 
      dockerfile: ./Dockerfile    
    ports:
      - 8080:8088
    environment:
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookstore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bookstore
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bookstore-spring-postgres
  db:
    image: postgres:16
    restart: always
    volumes:
      - bookstore-db-data:/var/lib/postgresql/data
    networks:
      - bookstore-spring-postgres
    environment:
      - POSTGRES_DB=bookstore
      - POSTGRES_PASSWORD=bookstore
    expose:
      - 5432
  pgadmin:
    container_name: bookstore-pgadmin
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_not_used@user.com
      PGADMIN_DEFAULT_PASSWORD: admin_not_used
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - bookstore-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - bookstore-spring-postgres
    restart: always      
volumes:
  bookstore-db-data:
  bookstore-pgadmin:
networks:
  bookstore-spring-postgres: