services:
  backend:
    image: person_backend:liberica-openjdk
    build: 
      dockerfile: ./Dockerfile    
    ports:
      - 8080:8088
    environment:
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/person
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=person
      - SPRING_H2_CONSOLE_ENABLED=false
      - SPRING_SQL_INIT_PLATFORM=postgresql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - person-spring-postgres
  db:
    image: postgres:16
    restart: always
    volumes:
      - person-db-data:/var/lib/postgresql/data
    networks:
      - person-spring-postgres
    environment:
      - POSTGRES_DB=person
      - POSTGRES_PASSWORD=person
    expose:
      - 5432
  pgadmin:
    container_name: person-pgadmin
    image: dpage/pgadmin4:8.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_not_used@user.com
      PGADMIN_DEFAULT_PASSWORD: admin_not_used
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - person-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - person-spring-postgres
    restart: always 
volumes:
  person-db-data:
  person-pgadmin:
networks:
  person-spring-postgres: