version: "3.8"

services:
  traefik:
    image: traefik:latest  # As of March 2025, pulls the latest Traefik v2.x
    container_name: traefik
    ports:
      - "80:80"  # Expose Traefik on port 80
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro  # Static config
      - ./config.yml:/etc/traefik/config.yml:ro     # Dynamic config
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge
