entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"  # For dashboard

providers:
  file:
    filename: "/etc/traefik/config.yml"
    watch: true

log:
  level: INFO

api:
  dashboard: true    # Enable dashboard
  insecure: true     # No authentication, open access