services:
  backend:
    image: spring-boot-jpa-vue_backend:aws-alpine
    build: 
      dockerfile: ./Dockerfile    
    ports:
      - 8080:8088
    environment:
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/example
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass-example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JOINFACES_FACES_SERVLET_ENABLED=true
      - JOINFACES_FACES_AUTOMATIC_EXTENSIONLESS_MAPPING=true
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    deploy:
      resources:
        limits:
          cpus: 1.0
          memory: 640M
        reservations:
          cpus: 0.5
          memory: 256M       
    networks:
      - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=pass-example
      - PGADMIN_DEFAULT_EMAIL=admin_not_used@user.com
      - PGADMIN_DEFAULT_PASSWORD=admin_not_used
      - PGADMIN_CONFIG_SERVER_MODE="False"
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED="False"
    expose:
      - 5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_not_used@user.com
      PGADMIN_DEFAULT_PASSWORD: admin_not_used
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - spring-postgres
    restart: always      
volumes:
  db-data:
  pgadmin:
networks:
  spring-postgres: